version: '1.0'
services:
  db:
    container_name: db
    build:
      context: ./postgres-custom
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./containers/pg:/var/lib/postgresql/data
    networks:
      - local

networks:
  local:
    external: true
