version: '1.0'
services:
  db:
    container_name: db
    build:
      context: ./postgres-custom
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./containers/pg:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kaidstor@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8080:80
    volumes:
      - ./containers/pgadmin:/var/lib/pgadmin
      